### ISSUE TITLE
çalıştırma sorunu

### ISSUE THREAD

**Issue by Ferdi898** [apdullahyayik/Multi-Layer-Perceptron#1]
Hocam merhabalar;

Matlab kodunuzu çalıştırırken aşağıdaki gibi bir hata aldım. Matlab ta yeni olduğum için tam anlayamadım bakabilirmisiniz?. ek olarak ben switch-case yapılarınıza adam ve memory aktivasyon fonksiyonlarını ekleyerek dataları eğitebilirmiyim? 

>> mlptest
Error using load
Unable to read file 'm'. No such file or directory.

Error in mlptest (line 27)
load m
 
>> 

![abdullah hoca](https://user-images.githubusercontent.com/47475897/119654969-b0928780-be31-11eb-86f4-48bb6da40d95.png)

**Comment by apdullahyayik** [comment]
Sanırım eğitim yapmadın ya da "m" ağırlıklar kaydedilemedi

Öncelikle mlptgm.m i kullanarak ağırlıkları oluşturman gerekiyor.  Gördüğüm kadarıyla "m" olarak kaydediyor (`save m m`). Ardından bu ağırlıklar ı mlptest ile kullanabilirsin (`load m`). Verilerin formatının docstring lerde olduğu gibi olduğuna dikkat ediniz.

Gözden geçirip dönüş yapar mısın?

**Comment by Ferdi898** [comment]
Hocam merhabalar tekrardan 

mlptgm.m de  örnek kullanımları yaptım fakat yine syntax error veriyor hocam sanırım ben beceremedim çalıştırmayı. Örnek kullanımda başka bir şeyi değiştirmem gerekiyor mu ? yoksa direk kullanabilirmiyim

**Comment by apdullahyayik** [comment]
Aldığın hata nedir tam olarak paylaşır mısın?


Ayrıca eğitim setini attacment olark ekler misin? Aynı hayatı reproduce
etmem gerekiyor. Matlab ve OS versiyon ilgisi de verir misin.

**Comment by apdullahyayik** [comment]
Belirttiğine göre bir önceki hata filenotfound idi bu ise synyax error. Bu sebeple hatayı trace bilgisi ile birlikte yeniden yazar mısın.

**Comment by apdullahyayik** [comment]
Clos

**Comment by apdullahyayik** [comment]
Non-reproducable error notification.
